name: Scan an SBOM (package-lock.json)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check dependencies for security vulnerabilities
        uses: g-rath/check-with-osv-detector@main